(function(global){
class EnhancedPlayer{
  constructor(video,ui,statsEl){this.video=video;this.ui=ui;this.statsEl=statsEl;this.stream=null;this.title='';this.uiTimer=null;this.statsTimer=null;this.warmResult=null;this.startedAt=0;this.firstFrameAt=0;this.fallbackIndex=0;this.stallCount=0;this.stallStartedAt=0;this.totalStallMs=0;this.minBuffer=Infinity;this.maxBuffer=0;this.boundUpdate=()=>this.renderStats();this.onWaiting=()=>this.markStallStart();this.onPlaying=()=>this.markStallEnd();this.onTimeUpdate=()=>this.sampleBuffer();video.addEventListener('waiting',this.onWaiting);video.addEventListener('stalled',this.onWaiting);video.addEventListener('playing',this.onPlaying);video.addEventListener('timeupdate',this.onTimeUpdate)}
  resetSessionMetrics(){this.firstFrameAt=0;this.stallCount=0;this.stallStartedAt=0;this.totalStallMs=0;this.minBuffer=Infinity;this.maxBuffer=0}
  resetMedia(){try{this.video.pause()}catch(_){}this.video.removeAttribute('src');try{this.video.load()}catch(_){} }
  async waitUntilPlayable(timeoutMs){const v=this.video;return new Promise((resolve,reject)=>{let done=false;const finish=(err)=>{if(done)return;done=true;clearTimeout(timer);v.removeEventListener('canplay',ok);v.removeEventListener('loadedmetadata',ok);v.removeEventListener('error',bad);if(err)reject(err);else resolve()};const ok=()=>finish();const bad=()=>finish(new Error('A TV rejeitou esta fonte.'));const timer=setTimeout(()=>finish(new Error('Tempo limite ao iniciar esta fonte.')),timeoutMs||12000);v.addEventListener('canplay',ok,{once:true});v.addEventListener('loadedmetadata',ok,{once:true});v.addEventListener('error',bad,{once:true});if(v.readyState>=1)finish()})}
  async waitForFirstFrame(timeoutMs){const v=this.video;return new Promise((resolve,reject)=>{let done=false;let lastTime=v.currentTime;const finish=(err)=>{if(done)return;done=true;clearTimeout(timer);v.removeEventListener('timeupdate',tick);v.removeEventListener('playing',tick);v.removeEventListener('error',bad);if(err)reject(err);else resolve()};const tick=()=>{if(v.currentTime>lastTime||(!v.paused&&v.readyState>=3)){this.firstFrameAt=performance.now();finish()}lastTime=v.currentTime};const bad=()=>finish(new Error('Falha antes do primeiro frame.'));const timer=setTimeout(()=>finish(new Error('A fonte abriu, mas não iniciou vídeo a tempo.')),timeoutMs||10000);v.addEventListener('timeupdate',tick);v.addEventListener('playing',tick);v.addEventListener('error',bad,{once:true});tick()})}
  async open(stream,title){const url=NuvioStreams.sourceUrl(stream);if(!url)throw new Error('Esta fonte não fornece URL HTTP reproduzível pelo player da LG.');this.resetMedia();this.resetSessionMetrics();this.stream=stream;this.title=title||'';this.startedAt=performance.now();document.getElementById('player-title').textContent=this.title;document.getElementById('player-source').textContent=(stream._addonName||'')+' · '+NuvioStreams.displayName(stream);document.getElementById('player-overlay').classList.remove('hidden');this.showUI();if(localStorage.getItem('nuvioEnhanced.statsOpen')==='true')this.statsEl.classList.remove('hidden');this.warmResult=await NuvioStreams.warm(url,2200,262144);this.video.src=url;this.video.load();await this.waitUntilPlayable(14000);try{await this.video.play()}catch(_){}await this.waitForFirstFrame(10000);clearInterval(this.statsTimer);this.statsTimer=setInterval(this.boundUpdate,1000);this.renderStats();try{localStorage.setItem('nuvioEnhanced.lastStream',JSON.stringify({url:url,title:NuvioStreams.displayName(stream),addon:stream._addonName||'',at:Date.now()}))}catch(_){}return stream}
  async openCandidates(streams,title){const candidates=(streams||[]).filter(NuvioStreams.isPlayable).slice(0,6);if(!candidates.length)throw new Error('Nenhuma fonte com URL direta compatível com a LG.');let lastError=null;for(let i=0;i<candidates.length;i++){this.fallbackIndex=i;try{return await this.open(candidates[i],title)}catch(err){lastError=err;this.resetMedia();document.getElementById('player-source').textContent='Tentando fonte '+(i+2)+' de '+candidates.length+'…'}}throw lastError||new Error('Nenhuma fonte conseguiu iniciar.')}
  markStallStart(){if(!this.stream||this.video.seeking||this.video.paused||this.stallStartedAt)return;this.stallStartedAt=performance.now();this.stallCount++;this.showUI();this.renderStats()}
  markStallEnd(){if(!this.stallStartedAt){if(!this.firstFrameAt)this.firstFrameAt=performance.now();return}this.totalStallMs+=performance.now()-this.stallStartedAt;this.stallStartedAt=0;this.renderStats()}
  sampleBuffer(){const ahead=this.bufferedAhead();if(Number.isFinite(ahead)){this.minBuffer=Math.min(this.minBuffer,ahead);this.maxBuffer=Math.max(this.maxBuffer,ahead)}}
  close(){clearInterval(this.statsTimer);this.markStallEnd();this.resetMedia();this.stream=null;this.statsEl.classList.add('hidden');document.getElementById('player-overlay').classList.add('hidden')}
  toggle(){if(this.video.paused)this.video.play();else this.video.pause();this.showUI()}
  seek(seconds){if(Number.isFinite(this.video.duration))this.video.currentTime=Math.max(0,Math.min(this.video.duration,this.video.currentTime+seconds));this.showUI()}
  toggleStats(){this.statsEl.classList.toggle('hidden');this.renderStats()}
  showUI(){this.ui.classList.add('visible');clearTimeout(this.uiTimer);this.uiTimer=setTimeout(()=>this.ui.classList.remove('visible'),4500)}
  bufferedAhead(){const v=this.video;try{for(let i=0;i<v.buffered.length;i++)if(v.currentTime>=v.buffered.start(i)&&v.currentTime<=v.buffered.end(i))return Math.max(0,v.buffered.end(i)-v.currentTime)}catch(_){}return 0}
  estimatedBitrateMbps(){const bytes=Number(this.stream&&this.stream.behaviorHints&&this.stream.behaviorHints.videoSize||0);const duration=Number(this.video.duration||0);return bytes&&duration?bytes*8/duration/1e6:0}
  playbackQuality(){try{return this.video.getVideoPlaybackQuality?this.video.getVideoPlaybackQuality():{}}catch(_){return{}}}
  renderStats(){if(!this.stream)return;const v=this.video,q=this.playbackQuality(),ahead=this.bufferedAhead(),est=this.estimatedBitrateMbps(),text=[this.stream.title,this.stream.name,this.stream.description].filter(Boolean).join(' ');this.sampleBuffer();const host=(()=>{try{return new URL(NuvioStreams.sourceUrl(this.stream)).host}catch(_){return'—'}})();const hdr=/dolby[ .-]?vision|\bdv\b/i.test(text)?'Dolby Vision (fonte)':/hdr10\+|hdr10plus/i.test(text)?'HDR10+ (fonte)':/\bhdr\b/i.test(text)?'HDR (fonte)':'SDR/indefinido';const codec=/av1/i.test(text)?'AV1':/hevc|x265|h\.265/i.test(text)?'HEVC/H.265':/x264|h\.264|avc/i.test(text)?'AVC/H.264':'indefinido';const audio=/truehd.*atmos|atmos.*truehd/i.test(text)?'TrueHD Atmos':/truehd/i.test(text)?'TrueHD':/dts[ .-]?hd/i.test(text)?'DTS-HD':/dts:x/i.test(text)?'DTS:X':/eac3|dd\+/i.test(text)?'E-AC-3':/ac3|dd\b/i.test(text)?'AC-3':'indefinido';const dropped=q.droppedVideoFrames==null?'—':q.droppedVideoFrames;const total=q.totalVideoFrames||0;const dropPct=total?((Number(dropped)||0)/total*100).toFixed(2)+'%':'—';const startup=this.firstFrameAt?Math.max(0,(this.firstFrameAt-this.startedAt)/1000):0;const activeStall=this.stallStartedAt?(performance.now()-this.stallStartedAt):0;const stallSeconds=(this.totalStallMs+activeStall)/1000;const health=ahead>=20?'ótimo':ahead>=8?'bom':ahead>=3?'baixo':'crítico';const minBuffer=Number.isFinite(this.minBuffer)?this.minBuffer:0;const rows=[['Resolução',v.videoWidth&&v.videoHeight?v.videoWidth+'×'+v.videoHeight:'aguardando'],['Perfil fonte',NuvioStreams.describe(this.stream)],['Vídeo',codec],['HDR/DV',hdr],['Áudio',audio],['Buffer',ahead.toFixed(1)+' s · '+health],['Faixa de buffer',minBuffer.toFixed(1)+'–'+this.maxBuffer.toFixed(1)+' s'],['Bitrate estimado',est?est.toFixed(1)+' Mbps':'indefinido'],['Warm-up',this.warmResult&&this.warmResult.ok?this.warmResult.ms.toFixed(0)+' ms'+(this.warmResult.mbps?' · '+this.warmResult.mbps.toFixed(1)+' Mbps':''):'não mensurável'],['Primeiro frame',startup?startup.toFixed(2)+' s':'aguardando'],['Stalls',this.stallCount+' · '+stallSeconds.toFixed(1)+' s'],['Fallback',this.fallbackIndex?('#'+(this.fallbackIndex+1)):'não'],['Frames perdidos',String(dropped)+' · '+dropPct],['Ready state',String(v.readyState)],['Host',host],['Addon',this.stream._addonName||'—']];this.statsEl.innerHTML='<strong>Stats for Nerds · webOS</strong>'+rows.map(r=>'<div class="stats-row"><span>'+escapeHtml(r[0])+'</span><span>'+escapeHtml(r[1])+'</span></div>').join('');document.getElementById('playpause').textContent=v.paused?'Play':'Pause';document.getElementById('time-label').textContent=fmt(v.currentTime)+' / '+fmt(v.duration)}
}
function fmt(s){if(!Number.isFinite(s))return'00:00';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=Math.floor(s%60);return(h?h+':'+String(m).padStart(2,'0'):String(m).padStart(2,'0'))+':'+String(sec).padStart(2,'0')}
function escapeHtml(v){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]||c))}
global.EnhancedPlayer=EnhancedPlayer;
})(window);
