(function(global){
const RESOLUTION_SCORE={'2160p':500,'4k':500,'1080p':350,'720p':200,'480p':80};
const QUALITY_TERMS=[[/remux/i,180],[/blu[ .-]?ray|bluray/i,120],[/web[ .-]?dl|webdl/i,70],[/web[ .-]?rip|webrip/i,50],[/hdr10\+|hdr10plus/i,45],[/dolby[ .-]?vision|\bdv\b/i,42],[/\bhdr\b/i,35],[/hevc|x265|h\.265/i,25],[/av1/i,22],[/truehd|atmos/i,22],[/dts[ .-]?hd|dts:x/i,20],[/aac/i,4],[/cam|telesync|ts\b/i,-500]];
const RELEASE_GROUP_BONUS=[[/fraMeSToR|CiNEPHiLES|EPSiLON|WiLDCAT|KRaLiMaRKo/i,50],[/FLUX|HONE|NTb|CMRG|TEPES|playWEB/i,30]];
function textOf(stream){return[stream.name,stream.title,stream.description,stream.behaviorHints&&stream.behaviorHints.filename].filter(Boolean).join(' ')}
function qualityLabel(stream){const t=textOf(stream);if(/2160p|\b4k\b/i.test(t))return'4K';if(/1080p/i.test(t))return'1080p';if(/720p/i.test(t))return'720p';if(/480p/i.test(t))return'480p';return'AUTO'}
function score(stream){const t=textOf(stream);let value=0;for(const[term,points]of Object.entries(RESOLUTION_SCORE))if(t.toLowerCase().includes(term))value+=points;for(const[re,points]of QUALITY_TERMS)if(re.test(t))value+=points;for(const[re,points]of RELEASE_GROUP_BONUS)if(re.test(t))value+=points;const size=Number(stream.behaviorHints&&stream.behaviorHints.videoSize||0);if(size>60*1024**3)value+=25;else if(size>20*1024**3)value+=15;if(stream.url)value+=8;if(stream.ytId)value-=100;return value}
function rank(streams){return[...(streams||[])].sort((a,b)=>score(b)-score(a))} function displayName(stream){return stream.title||stream.name||(stream.behaviorHints&&stream.behaviorHints.filename)||'Fonte'}
function sizeLabel(stream){const n=Number(stream.behaviorHints&&stream.behaviorHints.videoSize||0);if(!n)return'';const gb=n/1024**3;return gb>=1?gb.toFixed(gb>=10?0:1)+' GB':(n/1024**2).toFixed(0)+' MB'} function sourceUrl(stream){if(stream.url)return stream.url;if(stream.externalUrl)return stream.externalUrl;return null}
async function warm(url,timeoutMs){if(!url)return{ok:false,reason:'no-url'};const controller=new AbortController();const started=performance.now();const timer=setTimeout(()=>controller.abort(),timeoutMs||2200);try{const res=await fetch(url,{method:'GET',headers:{Range:'bytes=0-65535'},cache:'no-store',signal:controller.signal});let bytes=0;try{bytes=(await res.arrayBuffer()).byteLength}catch(_){}const ms=Math.max(1,performance.now()-started);return{ok:res.ok||res.status===206,status:res.status,ms,bytes,mbps:bytes?(bytes*8/ms/1000):0}}catch(err){return{ok:false,reason:err&&err.name==='AbortError'?'timeout':'cors-or-network',ms:performance.now()-started}}finally{clearTimeout(timer)}}
async function findStreams(type,id,onAddonResult){const addons=NuvioAddons.load().filter(a=>((a.manifest&&a.manifest.resources)||[]).some(r=>(typeof r==='string'?r:r.name)==='stream'));const collected=[];await Promise.all(addons.map(async addon=>{try{const data=await NuvioAddons.getStreams(addon,type,id);const streams=(data.streams||[]).map(s=>Object.assign({_addonName:addon.name,_addonId:addon.id},s));collected.push(...streams);if(onAddonResult)onAddonResult(addon,streams,null)}catch(err){if(onAddonResult)onAddonResult(addon,[],err)}}));return rank(collected)}
global.NuvioStreams={rank,score,qualityLabel,displayName,sizeLabel,sourceUrl,warm,findStreams};})(window);
